import { Link } from "react-router-dom";

export default function About() {
  const signedIn = Boolean(localStorage.getItem("token"));
  return <main className="page about-page">
    <section className="about-hero"><div><span className="eyebrow">Built for thoughtful work</span><h1 className="title">A calmer place for<br/>ambitious ideas.</h1><p className="about-lead">Notely is a private thinking space that helps you capture a spark, shape it over time, and turn it into a meaningful next step.</p><div className="hero-actions"><Link className="button button-primary" to={signedIn ? "/" : "/signup"}>{signedIn ? "Open my workspace" : "Create your workspace"}</Link>{!signedIn && <Link className="button button-outline" to="/login">Sign in</Link>}</div></div><aside className="signal-panel" aria-label="Notely product capabilities"><div className="signal-top"><span className="live-dot"></span><span>YOUR THINKING SYSTEM</span><span>01 / 03</span></div><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="signal-core">*</div><div className="signal-label label-one">CAPTURE</div><div className="signal-label label-two">CLARIFY</div><div className="signal-label label-three">ACT</div></aside></section>
    <section className="future-grid"><article><span>01</span><h2>Find the signal</h2><p>Search across titles, ideas, and contexts without breaking your flow. Your knowledge stays accessible, never buried.</p></article><article><span>02</span><h2>Build momentum</h2><p>Capture a thought when it appears, then return to clarify its value and decide what deserves your attention.</p></article><article><span>03</span><h2>Own your workspace</h2><p>Your notes are scoped to your account and protected by authentication, so this is a space designed around you.</p></article></section>
    <section className="builder-card"><div><span className="eyebrow">The person behind Notely</span><h2>Built with curiosity and care.</h2><p>Notely is a full-stack product experiment by Lalit Kishor, combining product thinking, user experience, and secure web engineering.</p></div><div className="builder-signature"><strong>Lalit Kishor</strong><span>SWE @ PayPal</span></div></section>
  </main>;
}
