import { useContext, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import NoteContext from "../context/notes/noteContext";

const blank = { title: "", description: "", tag: "General" };
const relativeDate = date => { const days = Math.floor((Date.now() - new Date(date)) / 86400000); return days === 0 ? "Today" : days === 1 ? "Yesterday" : `${days} days ago`; };
function Icon({ name }) { const paths = { pin: <path d="M8 3h8l-1 5 3 3v2H6v-2l3-3-1-5Zm4 10v8"/>, edit: <><path d="m4 16 1.2-4.2L14.5 2.5a2.1 2.1 0 0 1 3 3l-9.3 9.3L4 16Z"/><path d="m12.5 4.5 3 3"/></>, trash: <><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5m4-5v5"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>; }
function IconButton({ label, icon, onClick, className = "" }) { return <button type="button" className={`icon-button ${className}`} aria-label={label} title={label} onClick={onClick}><Icon name={icon}/></button>; }

export default function Notes({ showAlert }) {
  const { notes, loading, getNotes, addNote, editNote, deleteNote, togglePin } = useContext(NoteContext);
  const navigate = useNavigate(); const [search, setSearch] = useState(""); const [tag, setTag] = useState("All"); const [sort, setSort] = useState("updated"); const [editor, setEditor] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!localStorage.getItem("token")) navigate("/login"); else getNotes().catch(error => showAlert(error.message, "danger")); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const tags = useMemo(() => ["All", ...new Set(notes.map(note => note.tag || "General"))], [notes]);
  const visible = useMemo(() => notes.filter(note => { const text = `${note.title} ${note.description} ${note.tag}`.toLowerCase(); return text.includes(search.toLowerCase()) && (tag === "All" || (note.tag || "General") === tag); }).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "created" ? new Date(b.createdAt || b.Date) - new Date(a.createdAt || a.Date) : Number(b.pinned) - Number(a.pinned) || new Date(b.updatedAt || b.Date) - new Date(a.updatedAt || a.Date)), [notes, search, tag, sort]);
  const submit = async event => { event.preventDefault(); setSaving(true); try { if (editor._id) await editNote(editor._id, editor.title, editor.description, editor.tag); else await addNote(editor.title, editor.description, editor.tag); setEditor(null); showAlert(editor._id ? "Note updated" : "Thought captured"); } catch (error) { showAlert(error.message, "danger"); } finally { setSaving(false); } };
  const remove = async note => { if (!window.confirm(`Delete "${note.title}"?`)) return; try { await deleteNote(note._id); showAlert("Note deleted"); } catch (error) { showAlert(error.message, "danger"); } };
  const openComposer = () => setEditor(blank);
  const onCardKeyDown = (event, note) => { if (event.target !== event.currentTarget) return; if (event.key === "Enter" || event.key === " ") { event.preventDefault(); navigate(`/notes/${note._id}`); } };
  return <main className="page"><section className="workspace-head"><div><span className="eyebrow">Your thought-to-action workspace</span><h1 className="title">Turn ideas into momentum.</h1><p className="subtitle">Capture what matters now. Clarify it when you are ready. Act with confidence.</p></div><button className="button button-primary" onClick={openComposer}>+ Capture thought</button></section>
    <section className="focus-banner"><div><span className="focus-kicker">YOUR WORKFLOW</span><h2>Capture <span>-&gt;</span> Clarify <span>-&gt;</span> Act</h2><p>Every meaningful outcome begins with one small thought. Start by getting it out of your head.</p></div><button className="button button-outline" onClick={openComposer}>Write it down</button></section>
    <section className="stats"><article className="stat"><span>Thoughts captured</span><strong>{notes.length}</strong></article><article className="stat"><span>In your focus</span><strong>{notes.filter(note => note.pinned).length}</strong></article><article className="stat"><span>Contexts organized</span><strong>{Math.max(0, tags.length - 1)}</strong></article></section>
    <section className="toolbar"><label className="search"><span>Search</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your thoughts..." /></label><select className="select" value={sort} onChange={e => setSort(e.target.value)}><option value="updated">Recently updated</option><option value="created">Recently created</option><option value="title">Title A-Z</option></select></section><div className="tag-row">{tags.map(item => <button key={item} onClick={() => setTag(item)} className={`tag-filter ${tag === item ? "selected" : ""}`}>{item}</button>)}</div>
    {loading ? <div className="empty"><div className="empty-icon">...</div><p>Gathering your notes...</p></div> : visible.length ? <><div className="collection-heading"><div><span className="eyebrow">Your captured context</span><h2>Thinking space</h2></div><span>{visible.length} {visible.length === 1 ? "note" : "notes"}</span></div><section className="notes-grid">{visible.map(note => <article className={`note-card ${note.pinned ? "pinned" : ""}`} key={note._id} tabIndex="0" role="button" onClick={() => navigate(`/notes/${note._id}`)} onKeyDown={event => onCardKeyDown(event, note)}><div className="card-actions" onClick={event => event.stopPropagation()}><IconButton label={note.pinned ? "Remove from focus" : "Add to focus"} icon="pin" className={note.pinned ? "pin" : ""} onClick={() => togglePin(note).catch(error => showAlert(error.message, "danger"))}/><IconButton label="Edit note" icon="edit" onClick={() => setEditor(note)}/><IconButton label="Delete note" icon="trash" onClick={() => remove(note)}/></div><span className="tag">{note.tag || "General"}</span><h3 title={note.title}>{note.title}</h3><p>{note.description}</p><div className="note-meta"><span>{relativeDate(note.updatedAt || note.Date)}</span><span>Open note</span></div></article>)}</section></> : <section className="empty"><div className="empty-icon">*</div><h2>{notes.length ? "Nothing matches that search" : "Your thinking space is ready"}</h2><p>{notes.length ? "Try another word or context." : "Capture one thought. You can turn it into a clear next step later."}</p>{!notes.length && <button className="button button-primary" onClick={openComposer}>Capture your first thought</button>}</section>}
    {editor && <div className="modal-backdrop" role="presentation"><form className="note-modal" onSubmit={submit}><div className="modal-head"><h2>{editor._id ? "Clarify thought" : "Capture a thought"}</h2><IconButton label="Close editor" icon="close" className="modal-close" onClick={() => setEditor(null)}/></div><div className="field"><label htmlFor="note-title">Title <span>{editor.title.length}/100</span></label><input id="note-title" autoFocus required minLength="3" maxLength="100" value={editor.title} onChange={e => setEditor({ ...editor, title: e.target.value })} placeholder="Give this thought a name (12 words max)" /></div><div className="field"><label htmlFor="note-tag">Context <span>{editor.tag.length}/32</span></label><input id="note-tag" maxLength="32" value={editor.tag} onChange={e => setEditor({ ...editor, tag: e.target.value })} placeholder="e.g. Work, Ideas, Personal" /></div><div className="field"><label htmlFor="note-description">Your thought</label><textarea id="note-description" required minLength="5" value={editor.description} onChange={e => setEditor({ ...editor, description: e.target.value })} placeholder="Start writing..." /></div><div className="form-actions"><button type="button" className="button button-quiet" onClick={() => setEditor(null)}>Cancel</button><button disabled={saving} className="button button-primary">{saving ? "Saving..." : "Save thought"}</button></div></form></div>}
  </main>;
}
